kind: role
version: v7
metadata:
  name: base
  description: "Base role: no standing privileges, request-only access"
spec:
  allow:
    request:
      roles:
        - okta_kube
        - okta_ssh
        - okta_ssh_root
      thresholds:
        - name: ssh auto-approval
          filter: 'contains(request.roles, "okta_ssh") && !contains(request.roles, "okta_ssh_root") && !contains(request.roles, "okta_kube")'
          approve: 1
          deny: 1
        - name: manual approval
          filter: 'contains(request.roles, "okta_ssh_root") || contains(request.roles, "okta_kube")'
          approve: 1
          deny: 1
      annotations:
        reason: '[{"required":true}]'
  deny: {}
  options:
    max_session_ttl: 8h
    lock: best_effort
