kind: cluster_auth_preference
version: v2
metadata:
  name: cluster-auth-preference
spec:
  type: saml
  connector_name: okta
  local_auth: true
  second_factor: "on"
  webauthn:
    rp_id: "grant-tam-teleport.gvteleport.com"
