kind: role
version: v7
metadata:
  name: okta_ssh
  description: "SSH access to team-labeled nodes, no root elevation"
spec:
  allow:
    logins:
      - ubuntu
    node_labels:
      team: '*'
    host_groups: []
    host_sudoers: []
  deny:
    logins:
      - root
    host_sudoers:
      - "*"
  options:
    max_session_ttl: 8h
    forward_agent: false
    port_forwarding: false
    enhanced_recording:
      - command
      - network
    permit_x11_forwarding: false
    lock: best_effort
    request_access: optional
